import qrcode
import streamlit as st
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification


MODEL_REPO = "ToastyKrawch/customer-support-ticket-distilbert"
MAX_LENGTH = 256
APP_URL = "https://customer-support-ticket-classifier-g6cwpvwwbfyr5fyw2vmv6m.streamlit.app/"


st.set_page_config(
    page_title="Customer Support Ticket Classifier",
    layout="centered"
)


@st.cache_resource
def load_model():
    tokenizer = AutoTokenizer.from_pretrained(MODEL_REPO)

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_REPO
    )

    model.eval()

    return tokenizer, model


tokenizer, model = load_model()


def predict_ticket(subject, body):
    text = f"{subject.strip()} {body.strip()}".strip()

    inputs = tokenizer(
        text,
        padding="max_length",
        truncation=True,
        max_length=MAX_LENGTH,
        return_tensors="pt"
    )

    with torch.no_grad():
        outputs = model(**inputs)

        probabilities = torch.softmax(
            outputs.logits,
            dim=-1
        )[0]

        predicted_id = torch.argmax(
            probabilities
        ).item()

    predicted_label = model.config.id2label[predicted_id]
    confidence = probabilities[predicted_id].item()

    return predicted_label, confidence


# -----------------------------
# Page content
# -----------------------------

st.title("Customer Support Ticket Classifier")

st.write(
    "Enter the subject and description of a customer support ticket. "
    "The model will classify the ticket into one of four categories."
)

st.subheader("Try it yourself")

st.write(
    "Scan the QR code with your phone to open the classifier "
    "and submit your own support ticket."
)

qr = qrcode.QRCode(
    version=None,
    box_size=8,
    border=4
)

qr.add_data(APP_URL)
qr.make(fit=True)

qr_image = qr.make_image(
    fill_color="black",
    back_color="white"
)

st.image(
    qr_image,
    caption="Scan to open the live application",
    width=220
)

with st.expander("What do the ticket types mean?"):
    st.markdown(
        """
        - **Incident** — An unexpected issue or service interruption that needs attention.
        - **Request** — A user asking for access, information, software, or another service.
        - **Change** — A request to modify an existing system, configuration, or service.
        - **Problem** — A recurring or underlying issue that may require further investigation.
        """
    )

st.divider()

with st.form("ticket_form"):
    subject = st.text_input(
        "Ticket Subject",
        placeholder="Example: Unable to connect to VPN"
    )

    body = st.text_area(
        "Ticket Description",
        height=180,
        placeholder=(
            "Describe the issue or request here..."
        )
    )

    submitted = st.form_submit_button(
        "Classify Ticket",
        use_container_width=True
    )


if submitted:
    if not subject.strip() and not body.strip():
        st.warning(
            "Please enter a ticket subject or description."
        )

    else:
        with st.spinner("Analyzing ticket..."):
            predicted_label, confidence = predict_ticket(
                subject,
                body
            )

        st.subheader("Prediction")

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "Ticket Type",
                predicted_label
            )

        with col2:
            st.metric(
                "Confidence",
                f"{confidence:.2%}"
            )

        st.progress(
            confidence,
            text=f"Model confidence: {confidence:.2%}"
        )

        st.caption(
            "The prediction is generated by a fine-tuned DistilBERT "
            "model and should be treated as decision support rather "
            "than a guaranteed classification."
        )

st.divider()

st.caption(
    "PROG74040 — Advanced Topics in Artificial Intelligence "
    "and Machine Learning | Group 8"
)
